SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `aspen`.`Users` 
CHANGE COLUMN `createdAt` `createdAt` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `updatedAt` `updatedAt` DATETIME NULL DEFAULT NULL ;

ALTER TABLE `aspen`.`Lectures` 
CHANGE COLUMN `createdAt` `createdAt` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `updatedAt` `updatedAt` DATETIME NULL DEFAULT NULL ;

ALTER TABLE `aspen`.`Subjects` 
CHANGE COLUMN `createdAt` `createdAt` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `updatedAt` `updatedAt` DATETIME NULL DEFAULT NULL ;

ALTER TABLE `aspen`.`LecturesUsers` 
CHANGE COLUMN `createdAt` `createdAt` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `updatedAt` `updatedAt` DATETIME NULL DEFAULT NULL ;

ALTER TABLE `aspen`.`SubmitStatuses` 
CHANGE COLUMN `createdAt` `createdAt` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `updatedAt` `updatedAt` TIMESTAMP NULL DEFAULT NULL ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
