SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `aspen`.`Users` 
ADD COLUMN `github_id` VARCHAR(45) NULL DEFAULT NULL AFTER `name`;

ALTER TABLE `aspen`.`Subjects` 
CHANGE COLUMN `dueDate` `startAt` DATETIME NULL DEFAULT NULL ,
ADD COLUMN `endAt` VARCHAR(45) NULL DEFAULT NULL AFTER `startAt`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
