cookie:
  secret: 'REPLACE SECRET IN DEVELOPMENT.YAML'
session:
  secret: 'REPLACE SECRET IN DEVELOPMENT.YAML'
db:
  host: 'localhost'
  user: 'root'
  password: ''
  database: 'aspen'
passport:
  host_url: ''
  github:
    client_id: ''
    client_secret: ''
