cookie:
  secret: 'REPLACE SECRET IN LOCAL.YAML'
db:
  host: 'localhost'
  user: 'root'
  password: ''
  database: 'aspen'
analytics:
  Analytics_UA: '' #e.g., UA-********-*
  Analytics_Domain: '' #e.g., www.example.com
passport:
  GITHUB_CLIENT_ID: ''
  GITHUB_CLIENT_SECRET: ''
