-- MySQL Script generated by MySQL Workbench
-- 10/03/14 16:01:56
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aspen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aspen` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `aspen` ;

-- -----------------------------------------------------
-- Table `aspen`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspen`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `github_id` VARCHAR(45) NULL,
  `studentNumber` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT now(),
  `updatedAt` DATETIME NOT NULL,
  `deleteFlag` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspen`.`Lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspen`.`Lectures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `startAt` DATETIME NOT NULL DEFAULT now(),
  `deleteFlag` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT now(),
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspen`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspen`.`Subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NULL,
  `content` LONGTEXT NOT NULL,
<<<<<<< HEAD
  `LectureId` INT NOT NULL,
=======
  `lectureId` INT NOT NULL,
>>>>>>> c1e5572b5159db746751c14059663cb9aefa6c3b
  `startAt` DATETIME NULL DEFAULT NULL,
  `endAt` DATETIME NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `deleteFlag` TINYINT(1) NOT NULL DEFAULT 0,
<<<<<<< HEAD
  PRIMARY KEY (`id`, `LectureId`),
  INDEX `fk_subject_lecture_idx` (`LectureId` ASC),
  CONSTRAINT `fk_subject_lecture`
    FOREIGN KEY (`LectureId`)
=======
  PRIMARY KEY (`id`, `lectureId`),
  INDEX `fk_subject_lecture_idx` (`lectureId` ASC),
  CONSTRAINT `fk_subject_lecture`
    FOREIGN KEY (`lectureId`)
>>>>>>> c1e5572b5159db746751c14059663cb9aefa6c3b
    REFERENCES `aspen`.`Lectures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspen`.`LecturesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspen`.`LecturesUsers` (
  `LectureId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT now(),
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`LectureId`, `UserId`),
  INDEX `fk_lecture_has_user_user1_idx` (`UserId` ASC),
  INDEX `fk_lecture_has_user_lecture1_idx` (`LectureId` ASC),
  CONSTRAINT `fk_lecture_has_user_lecture1`
    FOREIGN KEY (`LectureId`)
    REFERENCES `aspen`.`Lectures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecture_has_user_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `aspen`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspen`.`SubmitStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspen`.`SubmitStatuses` (
  `UserId` INT NOT NULL,
  `SubjectId` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL DEFAULT 0 COMMENT '0: Not yet, 1: Submitted, 2: Succeed',
  `content` LONGTEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deleteFlag` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `UserId`, `SubjectId`),
  INDEX `fk_user_has_subject_subject1_idx` (`SubjectId` ASC, `id` ASC),
  INDEX `fk_user_has_subject_user1_idx` (`UserId` ASC),
  CONSTRAINT `fk_user_has_subject_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `aspen`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_subject_subject1`
    FOREIGN KEY (`SubjectId` , `id`)
<<<<<<< HEAD
    REFERENCES `aspen`.`Subjects` (`id` , `LectureId`)
=======
    REFERENCES `aspen`.`Subjects` (`id` , `lectureId`)
>>>>>>> c1e5572b5159db746751c14059663cb9aefa6c3b
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
